language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install MySQL-python; fi
  - travis_retry pip install pymysql
  - travis_retry pip install -r test/requirements.txt
  - travis_retry pip install coveralls
  - travis_retry pip install .
script:
  - nosetests --verbose --with-coverage
after_success:
  - coveralls
